### ISSUE TITLE
Parse query parameters in addition to parameters passed in URL

### ISSUE THREAD

**Issue by hamza1311** [ibraheemdev/matchit#11]
Consider a path, `/path/:value/?foo=:bar` parsed with url `/path/test/?foo=something`. The library currently parses only `test` parameter. It should parse `foo` as well.

We're planning to use `matchit` in [Yew](https://yew.rs) (https://github.com/yewstack/yew/issues/2277) and this would be a very useful improvement.

**Comment by ibraheemdev** [comment]
Query parameters are generally handled outside of the router, because they are unordered key-value pairs. You can parse them into a hashmap with something like `serde_urlencoded`. Is there a reason you think this should be handled by the router instead?

**Comment by hamza1311** [comment]
If these are parsed by the router, the following would work:
```rust
#[derive(Routable)]
enum Route {
    #[at("/view/:id/?page=:page")]
    View {
        id: u32,
        page: u32,
    },
}
```
If were to implement this right now, we would have to mark `page` field as query and have to pass it's value separately.

As an added bonus, we could do the same for fragments so the following would also work:
```rust
#[derive(Routable)]
enum Route {
    #[at("/view/:id/?page=:page#:title")]
    View {
        id: u32,
        page: u32,
        title: String,
    },
}
```

**Comment by ibraheemdev** [comment]
You could merge the route and query params into a single map and fetch by name from there. Or you could recognize naned query parameters in the derive macro and fetch them separately.
