### ISSUE TITLE
Add path-tree to benches

### ISSUE THREAD

**Issue by Nugine** [ibraheemdev/matchit#14]
`path-tree` is another router based on radix trees. It's worth including it in the benchmarks.
https://github.com/viz-rs/path-tree

**Comment by ibraheemdev** [comment]
I benchmarked it a while ago, and I believe it was around 10x slower than matchit (but the fastest of any competitor). I'd accept a PR adding it if you're interested.

**Comment by Nugine** [comment]
Amazing! Before I start, I would like to ask why `matchit` is 10x faster than `path-tree`  since they are based on the same data structure.

**Comment by ibraheemdev** [comment]
I don't know enough about `path-tree` to say, but the tree used internally by `matchit` is _very_ heavily optimized.
