### ISSUE TITLE
Support escaping `:` and `*`

### ISSUE THREAD

**Issue by hgzimmerman** [ibraheemdev/matchit#23]
I'm using this library by proxy of Axum, and ran into an issue in that the router would not accept path segments that contained multiple `:` characters, greeting me with the error: `Invalid route "/Schemas/urn:ietf:params:scim:schemas:core:2.0:User": only one parameter is allowed per path segment`, corresponding to the `TooManyParams` error variant defined in this crate. 

Could either the syntax be altered to support escaping the `:` and `*` characters with a prefix like `\`, or have the insert method treat the whole path section as a literal if it doesn't start with a `:` or `*`, or add an `.insert_components()` function that takes a slice of `enum Component<'a>{Literal(&'a str), Param, Wildcard, Separator}` and uses that to determine the matching criteria?

**Comment by ibraheemdev** [comment]
I think escaping with `\` makes sense. `/prefix:parameter` is a valid route by the way, which makes the second option more difficult.

**Comment by DavidSouther** [comment]
Just opened this (and linked) from Axum. I would also like to propose using `/{id}` for path pattern matching, to align with the OpenAPI spec.

**Comment by ibraheemdev** [comment]
With the [release of 0.8](https://github.com/ibraheemdev/matchit/releases/tag/v0.8.0), the route parameter syntax has changed to use `{x}` or `{*x}`. You can escape literal `{` and `}` characters with `{{` and `}}` in static routes.
