### ISSUE TITLE
tests/tree.rs does not compile

### ISSUE THREAD

**Issue by chaslain** [ibraheemdev/matchit#24]
```
no method named `check_priorities` found for struct `Router` in the current scope
method not found in `Router<String>`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
tree.rs(112, 1): Error originated from macro call here
```
https://github.com/ibraheemdev/matchit/blob/fd2b5cdcd599bf62fa5cab7c1ba339802f8587fb/tests/tree.rs#L61

**Comment by chaslain** [comment]
Nevermind - I see this is hidden by a configuration. Closes #24

**Comment by ibraheemdev** [comment]
Yeah I couldn't really come up with a better way to do it.

**Comment by chaslain** [comment]
@ibraheemdev so how do you execute tests?

**Comment by ibraheemdev** [comment]
`cargo test --all-features`
