### ISSUE TITLE
clarify license in crate metadata

### ISSUE THREAD

**Issue by decathorpe** [ibraheemdev/matchit#32]
I'm working on including a package for this crate in Fedora Linux as a dependency of axum. During the review process, the license was flagged as being potentially inaccurate and / or incomplete - the crate does include license texts for both itself *and* for httprouter, but the crate metadata lists only "MIT" (this crate's license), and not "BSD-3-Clause" (the httprouter license).

This is not only a "problem" for distribution packages, but it will trip up users of tools like `cargo-license` or `cargo-deny`, which rely on this metadata being accurate, as well.

Asking for advice from Red Hat lawyers, it seems that at least for *our* purposes, we need to treat this crate as being licensed under the terms of both MIT and BSD-3-Clause (i.e. `license = "MIT AND BSD-3-Clause"`):

c.f. https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/QDQXYBY4OVYZQ4GHKRZN5KXAO7OWTWJX/

The important bits are:

> (...) The upstream project
> says it's based on httprouter and it could be that some of it is a
> close translation from Go to Rust. While the BSD licenses are not
> entirely clear on this issue I think you should assume that the Rust
> crate copies from httprouter in such a way that the httprouter license
> requirements are triggered.

and 

> (...) you should assume the License: field
> should include `BSD-3-Clause` as appropriate.

It is entirely possible that you don't want to make a corresponding change for the crate metadata in Cargo.toml, but it would be great if you could clarify this either way - especially the slightly confusing situation that the license *text* for httprouter is included in this project, but the license *itself* is not taken into account in the crate metadata.

**Comment by ibraheemdev** [comment]
I think this is just an oversight on my end, I'll update the license text.

**Comment by decathorpe** [comment]
Great, thank you! 🍻
