### ISSUE TITLE
failed to register Get route for /:path pattern: insertion failed due to conflict with previously registered route: //'

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [ibraheemdev/matchit#33]
Hi, I was having an issue with Cloudflare worker-rs router but then I realized that the error is coming from this dependency

Issue: https://github.com/cloudflare/workers-rs/issues/362

TL;DR:
How do I create such routing:
```rust
    Router::new()
        .get("/abc/:path", |_req, ctx| {
            Response::ok("Hello world")
        })
        .get("/:path", |_req, ctx| {
            Response::ok("Hello world2")
        })
        .run(req, env).await
```
Right now this is the error I'm getting:
```
panicked at 'failed to register Get route for /:path pattern: insertion failed due to conflict with previously registered route: //', /home/gytis/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/worker-0.0.17/src/router.rs:327:21
```

I'd be okay with a solution using matchit on its own but I am not sure how to wire it with Cloudflare just yet

**Comment by ibraheemdev** [comment]
workers-rs seems to be using [an old version of matchit](https://github.com/cloudflare/workers-rs/blob/main/worker/Cargo.toml#L22). Your routes should not conflict on the latest release.
