### ISSUE TITLE
Profile-Guided Optimization (PGO) results

### ISSUE THREAD

**Issue by zamazan4ik** [ibraheemdev/matchit#38]
Hi!

I did some benchmarks of Profile-Guided Optimization (PGO) on the library and want to share my results here. Test environment is Macbook M1 Pro. The first run was with `cargo bench`, and the second - with a PGO-optimized version of the library via `cargo pgo optimize bench`. The PGO profile was collected via `cargo pgo bench`, the results from this run does not influence the comparison (since I did them in a separate Criterion directory). Link to `cargo-pgo` - https://github.com/Kobzol/cargo-pgo .

The results of "Release" vs "Release + PGO" are here: https://pastebin.com/kDtPRK2Y . The only regression was found with "Routers/path-tree", other benchmarks are improved or left untouched.

I hope someone can find these results interesting. Maybe would be a good idea to write a note about PGO in README for the users who want to extract more performance from the library.

**Comment by ibraheemdev** [comment]
I'm going to close this for now because PGO is pretty experimental, but I appreciate your findings!
