### ISSUE TITLE
Question: support for fallback in routes with collisions?

### ISSUE THREAD

**Issue by asgpng** [ibraheemdev/matchit#4]
I came here from [cloudflare/workers-rs](https://github.com/cloudflare/workers-rs/blob/main/worker/src/router.rs#L5) and had a question about possible support for the following scenario:

Let's say I want to configure explicit routes, while also having a fallback handler, e.g.:
* `/home`
* `/foo`
* `/:fallback`

Today, this doesn't seem possible because `/:fallback` collides with other routes at the same hierarchy. A workaround is to introduce a short prefix like `/f/:fallback`, but it's a little clunky compared to the desired behavior of "match explicit routes when present, and fallback to others otherwise".

Interested in thoughts on the above scenario - would you classify it as outside the bounds of what this routing library is intending to support, or something that may make sense in a future release? Or perhaps I'm missing a clever workaround with wildcards that would help?

**Comment by ibraheemdev** [comment]
Hi, exciting to see `matchit` being used in cloudflare/workers-rs! This is something I plan on supporting, the current behavior is too strict. Routes are prioritized already, so it's definitely in scope. I'll try to get a release out soon.

**Comment by asgpng** [comment]
Cool, thanks for weighing in, and glad to hear it's in scope! Happy to engage on any follow-up / review / testing as needed.

**Comment by ibraheemdev** [comment]
This works as of 0.4.4 :tada:
