### ISSUE TITLE
`at` holding reference to `Request.uri().path()` prevents from using  `&mut Request`

### ISSUE THREAD

**Issue by dpc** [ibraheemdev/matchit#40]
I've implemented some routing using `astra` + `matchit`, and there's one clone that bothers me.

Basically - I always need to do `req.uri().path().clone()` because otherwise `Params` will hold a shared reference to `req`, and I need `&mut req` to read the body.

It seems much more frugal to clone the `params` (as they are often empty), than the whole `path`, but there's no way for `Params` to hold any owned data.

Seems to me that it would be possible to avoid it with converting `Params` to be:

```rust
struct Params<'k, V> {
  kind: ParamKind<'k, V>
}

struct Param<'k, V> {
    key: &'k [u8],
    value: V,
}

```

So it's possible to use both `Params<'k, &'v [u8]>` and `Params<'k, Vec<u8>>`. Quick sanity check says it's working: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7e61d76d43bb607053bb7a1b3fb40320

**Comment by dpc** [comment]
> Could you avoid the cloning completely by calling `req.into_parts()`? Thought this might be useful regardless, or some variation of #28.

Oh, yes. I missed it. Though the ergonomics of it will be a bit worse.

**Comment by ibraheemdev** [comment]
Closing this in favor of https://github.com/ibraheemdev/matchit/issues/28.
