### ISSUE TITLE
Enhancement Request: Dynamic Route Removal and Update Support in Matchit

### ISSUE THREAD

**Issue by bruno-ortiz** [ibraheemdev/matchit#44]
I am in the process of developing a system that enables the dynamic registration and removal of HTTP routes while the service is in operation.

While Matchit offers impressive functionality, it currently lacks the capability to remove and update routes. Is there a possibility of incorporating these features into the framework?

I understand that there are existing workarounds for this limitation, but having built-in support for these actions in the future would be greatly appreciated.

Thank you for your dedication and hard work!

**Comment by ibraheemdev** [comment]
I've heard of services that require this before, I'd happily accept a pull request implementing remove/update. As a first step, update can be implemented in terms of remove + insert. Also something to consider - removing a route could allow affected static nodes to be merged with their parent, though this could be implemented later.

**Comment by ibraheemdev** [comment]
Released in 0.8.2. Thanks to @Totodore for their work on this!
