### ISSUE TITLE
upgrade regex?

### ISSUE THREAD

**Issue by dakom** [ibraheemdev/matchit#48]
Reading https://portswigger.net/daily-swig/rust-patches-sneaky-redos-bug

Seems there might be a vulnerability lurking in regex, which was only patched from `1.5.5` onwards?

In any case - any reason not to be on latest `1.10`?

**Comment by davidpdrsn** [comment]
Note that regex is only a dev dependency and not used when you depend on matchit.

**Comment by dakom** [comment]
d'oh! good point 😅 - closing this issue
