### ISSUE TITLE
Implement `ExactSizeIterator` for `ParamsIter` or `Index` for `Params`

### ISSUE THREAD

**Issue by Totodore** [ibraheemdev/matchit#53]
Knowing the exact remaining length of  the iterator would be nice in my use case, I'm deserializing params to T with serde and I need to keep track of the remaining length.

Because `ParamsIter` only wraps an `std::slice::Iter`, and that it already implements [`ExactSizeIterator`](https://doc.rust-lang.org/std/slice/struct.Iter.html#impl-ExactSizeIterator-for-Iter%3C'_,+T%3E) we just have to forward the call to the inner `Iter`. 

Another way to solve my issue would have been to directly use `Params` but I cannot access any elements because it doesn't implement [`Index`](https://doc.rust-lang.org/std/ops/trait.Index.html).

What is your opinion on this @ibraheemdev? If you are ok with any of these two solution I will be happy to implement them.

**Comment by ibraheemdev** [comment]
Implementing `ExactSizeIterator` seems reasonable.
