### ISSUE TITLE
Allow merging two matchit Routers

### ISSUE THREAD

**Issue by jplatte** [ibraheemdev/matchit#57]
axum currently does a bunch of extra bookkeeping of its own in order to be able to merge two of its own `Router`s. I think some of this could be simplified if there was some functionality in matchit to merge two `matchit::Router`s. Would you consider a PR for this?

**Comment by ibraheemdev** [comment]
That seems reasonable, I would accept a PR for this.

**Comment by jplatte** [comment]
Any implementation hints? ^^
I took a brief look at this, but it doesn't seem straight-forward without understanding the internals of matchit's data structure(s). Is there a document going into that anywhere?

**Comment by ibraheemdev** [comment]
matchit is a standard prefix trie internally. I think the simplest way to implement this is to create an internal iterator and call `insert` for every route. A true efficient merge is a little more complex as you have to handle splitting prefixes recursively.

**Comment by ibraheemdev** [comment]
Released in 0.8.5.
