### ISSUE TITLE
Getting `Only one parameter is allowed per path segment` for valid route

### ISSUE THREAD

**Issue by cemoktra** [ibraheemdev/matchit#59]
The following example should be a valid route with two parameters in two segments.
```
let mut router = matchit::Router::new();
let result = router.insert("cards/{cardReferenceToken}/authorizationholds/{authorizationHoldExternalReferenceId}:decrease", true);
match result {
    Ok(_) => {},
    Err(err) => panic!("That should work but ended in: {err}"),
}
```

For reference:
https://api.mambu.com/#cards-decreaseauthorizationhold

**Comment by cemoktra** [comment]
any idea how to workaround this? i cannot change our whole backend away from axum now, but i need to support this case in the server code generator

**Comment by ibraheemdev** [comment]
For now you can parse the suffix manually from the `{authorizationHoldExternalReferenceId}` parameter.

**Comment by ibraheemdev** [comment]
Closing in favor of https://github.com/ibraheemdev/matchit/issues/17.
