### ISSUE TITLE
Why not balanced binary search tree?

### ISSUE THREAD

**Issue by kingluo** [ibraheemdev/matchit#6]
Why not use a binary search tree just like what Nginx does? In the Nginx way, the paths at the same level are sorted in a balanced binary tree, while the subtree (also balanced binary tree) stores sub nodes with the same common prefix.
In the radix tree, it seems that at the same level, it compares the node value one by one?

**Comment by ibraheemdev** [comment]
For a set of routes as large as Github's public API, the largest indice set contains around 15-20 elements. A binary search on this set only outperforms a linear search by around 5ns. On smaller arrays, linear search generally outperforms binary search, largely due the affects of branch misprediction. Add the fact that the indices are sorted by priority into the mix, and I think the current model will outperform binary search in most scenarios.

If you have further thoughts feel free to reopen this issue :)
